# Generated by Django 5.1 on 2024-08-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('General', 'General Election'), ('Department', 'Department Election'), ('Course', 'Course Election')], default='General', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional for general elections.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('school_level', models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HNG1', 'HNG1'), ('HNG2', 'HNG2')], max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('manifesto', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/images/')),
                ('course_studying', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='The department the candidate belongs to.', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['election'], name='elections_c_electio_b37bcc_idx')],
            },
        ),
    ]
