# Generated by Django 5.1 on 2024-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_remove_candidate_course_studying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Finished', 'Finished')], default='Upcoming', max_length=10),
        ),
    ]
