# Generated by Django 5.1 on 2024-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='votes_count',
        ),
        migrations.RemoveField(
            model_name='election',
            name='title',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school_level',
            field=models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1', 'HND1'), ('HND2', 'HND2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('The president', 'Presidential Election'), ('The vp', 'Vice President Election (follow southe)'), ('The treasurer', 'Treasurer Election'), ('The Pro', 'PRO Election'), ('The General secretary', 'General Secretary Election'), ('The Financial Secretary', 'Financial Secretary Election'), ('The Welfare Officer', 'Welfare Officer Election'), ('The assistant General secretary', 'Assistant General Secretary Election')], default='The president', max_length=200),
        ),
    ]
