# Generated by Django 5.1 on 2024-09-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_remove_candidate_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='department',
        ),
    ]
