# Generated by Django 5.1 on 2024-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_remove_election_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
