# Generated by Django 5.1 on 2024-09-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_rename_created_at_vote_voted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='matriculation_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
