# Generated by Django 5.1 on 2024-09-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_candidate_matriculation_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-start_date'], 'verbose_name': 'Election', 'verbose_name_plural': '     Elections'},
        ),
    ]
