# Generated by Django 5.1 on 2024-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_alter_vote_candidate_alter_vote_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates_images/'),
        ),
    ]
