# Generated by Django 5.1 on 2024-08-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard'), ('can_manage_users', 'Can manage users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users')]},
        ),
    ]
