# Generated by Django 5.1 on 2024-08-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', 'full_name'], 'permissions': [('can_view_dashboard', 'Can view dashboard'), ('can_manage_users', 'Can manage users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users')]},
        ),
    ]
