# Generated by Django 5.1 on 2024-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_level',
            field=models.CharField(blank=True, choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HNG1', 'HNG1'), ('HNG2', 'HNG2')], max_length=10, null=True),
        ),
    ]
