# Generated by Django 5.1 on 2024-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_level',
            field=models.CharField(blank=True, choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1', 'HND1'), ('HND2', 'HND2')], max_length=10, null=True),
        ),
    ]
