# Generated by Django 5.1 on 2024-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='7c8bdbef11d840e6b13122ade5ee9ab8', max_length=64, unique=True),
        ),
    ]
